package nl.melonstudios.create.init;

import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SoundEvent;
import net.minecraftforge.fml.common.registry.ForgeRegistries;

public final class SoundInit {
    public static SoundEvent item_sandpaper_used;
    public static SoundEvent block_cog_ambient;
    public static SoundEvent block_press_activate;
    public static SoundEvent item_wrench_used_rotate;
    public static SoundEvent item_wrench_used_dismantle;
    public static SoundEvent block_millstone_ambient;
    public static SoundEvent contraption_assemble;
    public static SoundEvent contraption_assemble_compound;
    public static SoundEvent contraption_disassemble;
    public static SoundEvent blaze_munch;
    public static SoundEvent confirm;
    public static SoundEvent contraption_assemble_compounded_1;
    public static SoundEvent controller_click;
    public static SoundEvent controller_put;
    public static SoundEvent controller_take;
    public static SoundEvent copper_armor_equip;
    public static SoundEvent crafter_click;
    public static SoundEvent crafter_click_compounded_1;
    public static SoundEvent crafter_craft;
    public static SoundEvent cranking;
    public static SoundEvent cranking_compounded_1;
    public static SoundEvent crushing_1;
    public static SoundEvent crushing_2;
    public static SoundEvent crushing_3;
    public static SoundEvent deny;
    public static SoundEvent depot_plop;
    public static SoundEvent depot_slide;
    public static SoundEvent frogport_deposit;
    public static SoundEvent frogport_open;
    public static SoundEvent funnel_flap;
    public static SoundEvent funnel_flap_compounded_1;
    public static SoundEvent item_hatch;
    public static SoundEvent item_hatch_compounded_1;
    public static SoundEvent mechanical_press_activation;
    public static SoundEvent mechanical_press_activation_belt;
    public static SoundEvent mechanical_press_activation_belt_compounded_1;
    public static SoundEvent mechanical_press_activation_compounded_1;
    public static SoundEvent mixing;
    public static SoundEvent mixing_compounded_1;
    public static SoundEvent package_pop;
    public static SoundEvent package_pop_compounded_1;
    public static SoundEvent packager;
    public static SoundEvent peculiar_bell_use;
    public static SoundEvent potato_hit;
    public static SoundEvent potato_hit_compounded_1;
    public static SoundEvent saw_activate_stone;
    public static SoundEvent saw_activate_wood;
    public static SoundEvent schematicannon_finish;
    public static SoundEvent schematicannon_launch_block;
    public static SoundEvent scroll_value;
    public static SoundEvent slime_added;
    public static SoundEvent worldshaper_place;
    public static SoundEvent wrench_remove;
    public static SoundEvent wrench_remove_compounded_1;
    public static SoundEvent wrench_rotate;
    public static void init() {
        item_sandpaper_used = registerSound("item.sandpaper.used");
        block_cog_ambient = registerSound("block.cog.ambient");
        block_press_activate = registerSound("block.press.activate");
        item_wrench_used_rotate = registerSound("item.wrench.used.rotate");
        item_wrench_used_dismantle = registerSound("item.wrench.used.dismantle");
        block_millstone_ambient = registerSound("block.millstone.ambient");
        contraption_assemble = registerSound("contraption.assemble");
        contraption_assemble_compound = registerSound("contraption.assemble.compound");
        contraption_disassemble = registerSound("contraption.disassemble");
        blaze_munch = registerSound("blaze_munch");
        confirm = registerSound("confirm");
        contraption_assemble_compounded_1 = registerSound("contraption_assemble_compounded_1");
        controller_click = registerSound("controller_click");
        controller_put = registerSound("controller_put");
        controller_take = registerSound("controller_take");
        copper_armor_equip = registerSound("copper_armor_equip");
        crafter_click = registerSound("crafter_click");
        crafter_click_compounded_1 = registerSound("crafter_click_compounded_1");
        crafter_craft = registerSound("crafter_craft");
        cranking = registerSound("cranking");
        cranking_compounded_1 = registerSound("cranking_compounded_1");
        crushing_1 = registerSound("crushing_1");
        crushing_2 = registerSound("crushing_2");
        crushing_3 = registerSound("crushing_3");
        deny = registerSound("deny");
        depot_plop = registerSound("depot_plop");
        depot_slide = registerSound("depot_slide");
        frogport_deposit = registerSound("frogport_deposit");
        frogport_open = registerSound("frogport_open");
        funnel_flap = registerSound("funnel_flap");
        funnel_flap_compounded_1 = registerSound("funnel_flap_compounded_1");
        item_hatch = registerSound("item_hatch");
        item_hatch_compounded_1 = registerSound("item_hatch_compounded_1");
        mechanical_press_activation = registerSound("mechanical_press_activation");
        mechanical_press_activation_belt = registerSound("mechanical_press_activation_belt");
        mechanical_press_activation_belt_compounded_1 = registerSound("mechanical_press_activation_belt_compounded_1");
        mechanical_press_activation_compounded_1 = registerSound("mechanical_press_activation_compounded_1");
        mixing = registerSound("mixing");
        mixing_compounded_1 = registerSound("mixing_compounded_1");
        package_pop = registerSound("package_pop");
        package_pop_compounded_1 = registerSound("package_pop_compounded_1");
        packager = registerSound("packager");
        peculiar_bell_use = registerSound("peculiar_bell_use");
        potato_hit = registerSound("potato_hit");
        potato_hit_compounded_1 = registerSound("potato_hit_compounded_1");
        saw_activate_stone = registerSound("saw_activate_stone");
        saw_activate_wood = registerSound("saw_activate_wood");
        schematicannon_finish = registerSound("schematicannon_finish");
        schematicannon_launch_block = registerSound("schematicannon_launch_block");
        scroll_value = registerSound("scroll_value");
        slime_added = registerSound("slime_added");
        worldshaper_place = registerSound("worldshaper_place");
        wrench_remove = registerSound("wrench_remove");
        wrench_remove_compounded_1 = registerSound("wrench_remove_compounded_1");
        wrench_rotate = registerSound("wrench_rotate");
    }

    private static SoundEvent registerSound(String registry) {
        ResourceLocation rsl = new ResourceLocation("create", registry);
        SoundEvent soundEvent = new SoundEvent(rsl);
        soundEvent.setRegistryName(registry);
        ForgeRegistries.SOUND_EVENTS.register(soundEvent);
        return soundEvent;
    }

    private SoundInit() {
        throw new AssertionError("no");
    }
}
